"""Creating new tenant table

Revision ID: d6619ec23234
Revises:
Create Date: 2022-07-12 00:12:39.538505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6619ec23234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tenants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('object_id', sa.Integer(), nullable=True),
        sa.Column('object_name', sa.String(), nullable=True),
        sa.Column('object_address', sa.String(), nullable=True),
        sa.Column('tenant_name', sa.String(), nullable=True),
        sa.Column('apartment_number', sa.String(), nullable=True),
        sa.Column('rent_start', sa.String(), nullable=True),
        sa.Column('rent_end', sa.String(), nullable=True),
        sa.Column('rent_price', sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    # ### end Alembic commands ###
